name = "calendar-worker"
type = "webpack"
workers_dev = true
site = {bucket = "./static",entry-point = "workers-site"}
compatibility_date = "2021-12-17"

[env.production]
name = "calendar-worker-production"
route = "files.motorsportcalendars.com/*"